version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bidichk
    - contextcheck
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - gocritic

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: exported
      - name: package-comments
